// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvtosauzubrdewdcicss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2dG9zYXV6dWJyZGV3ZGNpY3NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczNDc2MTEsImV4cCI6MjA1MjkyMzYxMX0.0prOJlY_a6Hzq1rhaKbK5zDn_R0GyTrJW2hSlx9-em4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
